# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.138.4+1.21.10
modmenu_version=16.0.0
clothconfig_version=20.0.149

minecraft_range=>=1.21.9 <=1.21.10